# nixpacks.toml

[phases.setup]
nixpkgs = ["rustc", "cargo", "build-essential"] # Install Rust toolchain and necessary build tools

[phases.build]
commands = [
  "pip install -r requirements.txt",  # Install Python dependencies
  "maturin develop"                    # Build Rust extensions (if any)
]
